version: '3.8'

services:
  front:
    build: .
    command: npm run start
    restart: always
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - './:/app'
      - '/app/node_modules'
    environment:
      NODE_OPTIONS: "--openssl-legacy-provider"
